version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    
  backend:
    build:
      context: .
      dockerfile: ./back.fargate.Dockerfile
    environment:
      - LOG_LEVEL=value
    secrets:
      - key
      - cert
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
      - 5678:5678
    tty: true
    stdin_open: true
    depends_on:
      - postgres
    command:
      - /bin/sh
      - -c
      - >-
        echo 'Alembic migration'
        && alembic upgrade head
        && echo 'Starting server'
        && python app/main.py

  fe-prod-build:
    build:
      context: .
      dockerfile: ./front.fargate.Dockerfile
    env_file:
      - ./frontend/.env
    secrets:
      - key
      - cert
      - root
    ports:
      - 3000:3000
    entrypoint: ["npm", "run", "start"]

secrets:
  key:
    file: ~/Development/ssl/localhost_certs/local-docker-key.pem
  cert:
    file: ~/Development/ssl/localhost_certs/local-docker-cert.pem
  root:
    file: ~/Library/Application Support/mkcert/rootCA.pem