version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fullstack-remix
    
  backend:
    build:
      context: .
      dockerfile: ./dev.back.Dockerfile
    environment:
      - LOG_LEVEL=value
    secrets:
      - key
      - cert
    env_file:
      - .env.back.dev
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
      - 5678:5678
    tty: true
    stdin_open: true
    entrypoint: ["python", "app/main.py"]
    depends_on:
      - postgres

secrets:
  key:
    file: ~/Development/ssl/localhost_certs/local-docker-key.pem
  cert:
    file: ~/Development/ssl/localhost_certs/local-docker-cert.pem