"""add cascade to models

Revision ID: V20240308__1
Revises: V20240224__3
Create Date: 2024-03-08 22:58:20.862196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'V20240308__1'
down_revision = 'V20240224__3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_expense_logs_expense_id_expenses', 'expense_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_expense_logs_expense_id_expenses'), 'expense_logs', 'expenses', ['expense_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_invoice_logs_invoice_id_invoices', 'invoice_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_invoice_logs_invoice_id_invoices'), 'invoice_logs', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_invoice_logs_invoice_id_invoices'), 'invoice_logs', type_='foreignkey')
    op.create_foreign_key('fk_invoice_logs_invoice_id_invoices', 'invoice_logs', 'invoices', ['invoice_id'], ['id'])
    op.drop_constraint(op.f('fk_expense_logs_expense_id_expenses'), 'expense_logs', type_='foreignkey')
    op.create_foreign_key('fk_expense_logs_expense_id_expenses', 'expense_logs', 'expenses', ['expense_id'], ['id'])
    # ### end Alembic commands ###
