"""add invoice and invoice log

Revision ID: V20240224__3
Revises: V20240224__2
Create Date: 2024-02-24 22:00:05.067171

"""
from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'V20240224__3'
down_revision = 'V20240224__2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'invoices',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=64), nullable=False),
        sa.Column('description', sa.String(length=200), nullable=True),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('currency_code', sa.String(length=10), nullable=False),
        sa.Column('attachment', sa.String(length=200), nullable=True),
        sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_invoices_user_id_user')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    op.create_table(
        'invoice_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=64), nullable=False),
        sa.Column('description', sa.String(length=200), nullable=True),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('currency_code', sa.String(length=10), nullable=False),
        sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column('invoice_id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_logs_invoice_id_invoices')),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_invoice_logs_user_id_user')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_logs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_logs')
    op.drop_table('invoices')
    # ### end Alembic commands ###
